server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentalplatformdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
jwt:
  secret: 8kuunS6IaBPePyisBoTl9Qa3uQbuEM3+szIgYQyijBrwQxTuuKfDdaM00sa+raqlgKkCJ1J6mJB3kfC6XXJI4g==
  expiration: 900000
